image:
  repository: ghcr.io/runvibe/cloudvibe-database-operator
  tag: latest
  pullPolicy: Always

serviceAccount:
  annotations: {}

env:
  rustLog: info
  otlpEndpoint: ""

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
